services:
  # 1. FAST API BACKEND
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lipstick-backend.rule=Host(`api-lipstick.spacelix.qzz.io`)"
      - "traefik.http.routers.lipstick-backend.entrypoints=websecure"
      - "traefik.http.routers.lipstick-backend.tls=true"
      - "traefik.http.services.lipstick-backend.loadbalancer.server.port=8000"

  # 2. FRONTEND NEXT.JS
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://api-lipstick.spacelix.qzz.io
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lipstick-frontend.rule=Host(`lipstick.spacelix.qzz.io`)"
      - "traefik.http.routers.lipstick-frontend.entrypoints=websecure"
      - "traefik.http.routers.lipstick-frontend.tls=true"
      - "traefik.http.services.lipstick-frontend.loadbalancer.server.port=3000"

networks:
  traefik-public:
    external: true
