import math

lipstick_database = [
    {"shade_name": "Bold Raspberry", "category": "Berry", "rgb_r": 150, "rgb_g": 81, "rgb_b": 143, "lip_type_tag": "Pinkish"},
    {"shade_name": "Glossy Berry", "category": "Berry", "rgb_r": 167, "rgb_g": 97, "rgb_b": 101, "lip_type_tag": "Pinkish"},
    {"shade_name": "Modern Berry", "category": "Berry", "rgb_r": 177, "rgb_g": 60, "rgb_b": 121, "lip_type_tag": "Pinkish"},
    {"shade_name": "Gentle Raspberry", "category": "Berry", "rgb_r": 178, "rgb_g": 93, "rgb_b": 132, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dewy Berry", "category": "Berry", "rgb_r": 187, "rgb_g": 104, "rgb_b": 104, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dreamy Mulberry", "category": "Berry", "rgb_r": 191, "rgb_g": 112, "rgb_b": 131, "lip_type_tag": "Pinkish"},
    {"shade_name": "Glossy Raspberry", "category": "Berry", "rgb_r": 192, "rgb_g": 107, "rgb_b": 114, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Mulberry", "category": "Berry", "rgb_r": 192, "rgb_g": 114, "rgb_b": 181, "lip_type_tag": "Pinkish"},
    {"shade_name": "Gentle Berry", "category": "Berry", "rgb_r": 193, "rgb_g": 110, "rgb_b": 111, "lip_type_tag": "Pinkish"},
    {"shade_name": "Matte Raspberry", "category": "Berry", "rgb_r": 194, "rgb_g": 116, "rgb_b": 130, "lip_type_tag": "Pinkish"},
    {"shade_name": "Chilled Logan", "category": "Berry", "rgb_r": 200, "rgb_g": 99, "rgb_b": 120, "lip_type_tag": "Pinkish"},
    {"shade_name": "Satin Raspberry", "category": "Berry", "rgb_r": 203, "rgb_g": 34, "rgb_b": 118, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Raspberry", "category": "Berry", "rgb_r": 203, "rgb_g": 122, "rgb_b": 132, "lip_type_tag": "Pinkish"},
    {"shade_name": "Radiant Raspberry", "category": "Berry", "rgb_r": 204, "rgb_g": 109, "rgb_b": 132, "lip_type_tag": "Pinkish"},
    {"shade_name": "Vibrant Boysenberry", "category": "Berry", "rgb_r": 204, "rgb_g": 77, "rgb_b": 104, "lip_type_tag": "Pinkish"},
    {"shade_name": "Satin Raspberry", "category": "Berry", "rgb_r": 204, "rgb_g": 74, "rgb_b": 107, "lip_type_tag": "Pinkish"},
    {"shade_name": "Gentle Mulberry", "category": "Berry", "rgb_r": 208, "rgb_g": 51, "rgb_b": 112, "lip_type_tag": "Pinkish"},
    {"shade_name": "Silky Raspberry", "category": "Berry", "rgb_r": 208, "rgb_g": 84, "rgb_b": 107, "lip_type_tag": "Pinkish"},
    {"shade_name": "Warm Mulberry", "category": "Berry", "rgb_r": 209, "rgb_g": 100, "rgb_b": 121, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dreamy Berry", "category": "Berry", "rgb_r": 209, "rgb_g": 84, "rgb_b": 110, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dewy Raspberry", "category": "Berry", "rgb_r": 210, "rgb_g": 67, "rgb_b": 121, "lip_type_tag": "Pinkish"},
    {"shade_name": "Bold Berry", "category": "Berry", "rgb_r": 211, "rgb_g": 97, "rgb_b": 121, "lip_type_tag": "Pinkish"},
    {"shade_name": "Cozy Berry", "category": "Berry", "rgb_r": 212, "rgb_g": 94, "rgb_b": 133, "lip_type_tag": "Pinkish"},
    {"shade_name": "Velvet Berry", "category": "Berry", "rgb_r": 216, "rgb_g": 112, "rgb_b": 125, "lip_type_tag": "Pinkish"},
    {"shade_name": "Chilled Berry", "category": "Berry", "rgb_r": 219, "rgb_g": 112, "rgb_b": 150, "lip_type_tag": "Pinkish"},
    {"shade_name": "Bold Raspberry", "category": "Berry", "rgb_r": 220, "rgb_g": 77, "rgb_b": 141, "lip_type_tag": "Pinkish"},
    {"shade_name": "Rich Mulberry", "category": "Berry", "rgb_r": 221, "rgb_g": 34, "rgb_b": 105, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dewy Mulberry", "category": "Berry", "rgb_r": 222, "rgb_g": 106, "rgb_b": 120, "lip_type_tag": "Pinkish"},
    {"shade_name": "Rich Berry", "category": "Berry", "rgb_r": 224, "rgb_g": 111, "rgb_b": 112, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dreamy Berry", "category": "Berry", "rgb_r": 224, "rgb_g": 24, "rgb_b": 107, "lip_type_tag": "Pinkish"},
    {"shade_name": "Soft Mulberry", "category": "Berry", "rgb_r": 224, "rgb_g": 85, "rgb_b": 114, "lip_type_tag": "Pinkish"},
    {"shade_name": "Cozy Bilberry", "category": "Berry", "rgb_r": 225, "rgb_g": 82, "rgb_b": 126, "lip_type_tag": "Pinkish"},
    {"shade_name": "Velvet Cranberry", "category": "Berry", "rgb_r": 227, "rgb_g": 78, "rgb_b": 144, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Mulberry", "category": "Berry", "rgb_r": 227, "rgb_g": 100, "rgb_b": 118, "lip_type_tag": "Pinkish"},
    {"shade_name": "Rich Logan", "category": "Berry", "rgb_r": 228, "rgb_g": 112, "rgb_b": 130, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dewy Berry", "category": "Berry", "rgb_r": 228, "rgb_g": 97, "rgb_b": 119, "lip_type_tag": "Pinkish"},
    {"shade_name": "Subtle Raspberry", "category": "Berry", "rgb_r": 230, "rgb_g": 105, "rgb_b": 157, "lip_type_tag": "Pinkish"},
    {"shade_name": "Sheer Raspberry", "category": "Berry", "rgb_r": 232, "rgb_g": 110, "rgb_b": 159, "lip_type_tag": "Pinkish"},
    {"shade_name": "Radiant Cranberry", "category": "Berry", "rgb_r": 232, "rgb_g": 117, "rgb_b": 147, "lip_type_tag": "Pinkish"},
    {"shade_name": "Warm Boysenberry", "category": "Berry", "rgb_r": 232, "rgb_g": 106, "rgb_b": 117, "lip_type_tag": "Pinkish"},
    {"shade_name": "Sheer Raspberry", "category": "Berry", "rgb_r": 233, "rgb_g": 108, "rgb_b": 129, "lip_type_tag": "Pinkish"},
    {"shade_name": "Vivid Berry", "category": "Berry", "rgb_r": 234, "rgb_g": 80, "rgb_b": 105, "lip_type_tag": "Pinkish"},
    {"shade_name": "Subtle Mulberry", "category": "Berry", "rgb_r": 234, "rgb_g": 88, "rgb_b": 111, "lip_type_tag": "Pinkish"},
    {"shade_name": "Bold Boysenberry", "category": "Berry", "rgb_r": 235, "rgb_g": 111, "rgb_b": 121, "lip_type_tag": "Pinkish"},
    {"shade_name": "Subtle Logan", "category": "Berry", "rgb_r": 235, "rgb_g": 99, "rgb_b": 107, "lip_type_tag": "Pinkish"},
    {"shade_name": "Bold Logan", "category": "Berry", "rgb_r": 235, "rgb_g": 92, "rgb_b": 151, "lip_type_tag": "Pinkish"},
    {"shade_name": "Warm Berry", "category": "Berry", "rgb_r": 236, "rgb_g": 106, "rgb_b": 112, "lip_type_tag": "Pinkish"},
    {"shade_name": "Rich Boysenberry", "category": "Berry", "rgb_r": 236, "rgb_g": 81, "rgb_b": 147, "lip_type_tag": "Pinkish"},
    {"shade_name": "Satin Logan", "category": "Berry", "rgb_r": 236, "rgb_g": 120, "rgb_b": 121, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Berry", "category": "Berry", "rgb_r": 236, "rgb_g": 98, "rgb_b": 146, "lip_type_tag": "Pinkish"},
    {"shade_name": "Radiant Mulberry", "category": "Berry", "rgb_r": 236, "rgb_g": 98, "rgb_b": 132, "lip_type_tag": "Pinkish"},
    {"shade_name": "Tender Berry", "category": "Berry", "rgb_r": 237, "rgb_g": 108, "rgb_b": 127, "lip_type_tag": "Pinkish"},
    {"shade_name": "Mellow Berry", "category": "Berry", "rgb_r": 238, "rgb_g": 116, "rgb_b": 134, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Logan", "category": "Berry", "rgb_r": 240, "rgb_g": 111, "rgb_b": 165, "lip_type_tag": "Pinkish"},
    {"shade_name": "Vibrant Berry", "category": "Berry", "rgb_r": 240, "rgb_g": 129, "rgb_b": 130, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dreamy Boysenberry", "category": "Berry", "rgb_r": 241, "rgb_g": 76, "rgb_b": 119, "lip_type_tag": "Pinkish"},
    {"shade_name": "Satin Cranberry", "category": "Berry", "rgb_r": 246, "rgb_g": 0, "rgb_b": 113, "lip_type_tag": "Pinkish"},
    {"shade_name": "Velvet Raspberry", "category": "Berry", "rgb_r": 247, "rgb_g": 94, "rgb_b": 112, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dewy Boysenberry", "category": "Berry", "rgb_r": 248, "rgb_g": 101, "rgb_b": 127, "lip_type_tag": "Pinkish"},
    {"shade_name": "Velvet Cranberry", "category": "Berry", "rgb_r": 250, "rgb_g": 97, "rgb_b": 115, "lip_type_tag": "Pinkish"},
    {"shade_name": "Subtle Bilberry", "category": "Berry", "rgb_r": 252, "rgb_g": 62, "rgb_b": 110, "lip_type_tag": "Pinkish"},
    {"shade_name": "Matte Logan", "category": "Berry", "rgb_r": 254, "rgb_g": 105, "rgb_b": 127, "lip_type_tag": "Pinkish"},
    {"shade_name": "Creamy Mulberry", "category": "Berry", "rgb_r": 255, "rgb_g": 84, "rgb_b": 163, "lip_type_tag": "Pinkish"},
    {"shade_name": "Radiant Mulberry", "category": "Berry", "rgb_r": 255, "rgb_g": 208, "rgb_b": 221, "lip_type_tag": "Pinkish"},
    {"shade_name": "Matte Cranberry", "category": "Berry", "rgb_r": 255, "rgb_g": 77, "rgb_b": 137, "lip_type_tag": "Pinkish"},
    {"shade_name": "Soft Tangerine", "category": "Coral", "rgb_r": 209, "rgb_g": 145, "rgb_b": 141, "lip_type_tag": "Pinkish"},
    {"shade_name": "Coral Glow", "category": "Coral", "rgb_r": 220, "rgb_g": 140, "rgb_b": 120, "lip_type_tag": "Pinkish"},
    {"shade_name": "Glossy Sunset", "category": "Coral", "rgb_r": 220, "rgb_g": 159, "rgb_b": 143, "lip_type_tag": "Pinkish"},
    {"shade_name": "Twilight Sunset", "category": "Coral", "rgb_r": 220, "rgb_g": 107, "rgb_b": 93, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Salmon", "category": "Coral", "rgb_r": 222, "rgb_g": 111, "rgb_b": 92, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dewy Coral", "category": "Coral", "rgb_r": 223, "rgb_g": 105, "rgb_b": 95, "lip_type_tag": "Pinkish"},
    {"shade_name": "Creamy Coral", "category": "Coral", "rgb_r": 224, "rgb_g": 108, "rgb_b": 104, "lip_type_tag": "Pinkish"},
    {"shade_name": "Gentle Melon", "category": "Coral", "rgb_r": 225, "rgb_g": 112, "rgb_b": 98, "lip_type_tag": "Pinkish"},
    {"shade_name": "Satin Tangerine", "category": "Coral", "rgb_r": 232, "rgb_g": 114, "rgb_b": 104, "lip_type_tag": "Pinkish"},
    {"shade_name": "Subtle Salmon", "category": "Coral", "rgb_r": 237, "rgb_g": 105, "rgb_b": 93, "lip_type_tag": "Pinkish"},
    {"shade_name": "Rich Peach", "category": "Coral", "rgb_r": 237, "rgb_g": 109, "rgb_b": 104, "lip_type_tag": "Pinkish"},
    {"shade_name": "Twilight Nectarine", "category": "Coral", "rgb_r": 239, "rgb_g": 124, "rgb_b": 107, "lip_type_tag": "Pinkish"},
    {"shade_name": "Glossy Peach", "category": "Coral", "rgb_r": 241, "rgb_g": 136, "rgb_b": 133, "lip_type_tag": "Pinkish"},
    {"shade_name": "Velvet Tangerine", "category": "Coral", "rgb_r": 241, "rgb_g": 115, "rgb_b": 101, "lip_type_tag": "Pinkish"},
    {"shade_name": "Rich Salmon", "category": "Coral", "rgb_r": 250, "rgb_g": 108, "rgb_b": 85, "lip_type_tag": "Pinkish"},
    {"shade_name": "Classic Tangerine", "category": "Coral", "rgb_r": 252, "rgb_g": 110, "rgb_b": 72, "lip_type_tag": "Pinkish"},
    {"shade_name": "Sheer Sunset", "category": "Coral", "rgb_r": 255, "rgb_g": 114, "rgb_b": 93, "lip_type_tag": "Pinkish"},
    {"shade_name": "Subtle Sunset", "category": "Coral", "rgb_r": 255, "rgb_g": 123, "rgb_b": 30, "lip_type_tag": "Pinkish"},
    {"shade_name": "Soft Nude", "category": "Nude", "rgb_r": 180, "rgb_g": 140, "rgb_b": 130, "lip_type_tag": "Pinkish"},
    {"shade_name": "Warm Almond", "category": "Nude", "rgb_r": 187, "rgb_g": 195, "rgb_b": 194, "lip_type_tag": "Pinkish"},
    {"shade_name": "Chilled Nude", "category": "Nude", "rgb_r": 239, "rgb_g": 233, "rgb_b": 222, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dusty Rose", "category": "Pink", "rgb_r": 185, "rgb_g": 115, "rgb_b": 125, "lip_type_tag": "Pinkish"},
    {"shade_name": "Blush Petal", "category": "Pink", "rgb_r": 195, "rgb_g": 125, "rgb_b": 145, "lip_type_tag": "Pinkish"},
    {"shade_name": "Rose Pink", "category": "Pink", "rgb_r": 200, "rgb_g": 120, "rgb_b": 140, "lip_type_tag": "Pinkish"},
    {"shade_name": "Warm Pink", "category": "Pink", "rgb_r": 210, "rgb_g": 130, "rgb_b": 150, "lip_type_tag": "Pinkish"},
    {"shade_name": "Cozy Cherry", "category": "Red", "rgb_r": 173, "rgb_g": 98, "rgb_b": 94, "lip_type_tag": "Pinkish"},
    {"shade_name": "Satin Vermillion", "category": "Red", "rgb_r": 173, "rgb_g": 95, "rgb_b": 86, "lip_type_tag": "Pinkish"},
    {"shade_name": "Bold Ruby", "category": "Red", "rgb_r": 176, "rgb_g": 88, "rgb_b": 86, "lip_type_tag": "Pinkish"},
    {"shade_name": "Warm Crimson", "category": "Red", "rgb_r": 185, "rgb_g": 100, "rgb_b": 99, "lip_type_tag": "Pinkish"},
    {"shade_name": "Velvet Cardinal", "category": "Red", "rgb_r": 189, "rgb_g": 81, "rgb_b": 84, "lip_type_tag": "Pinkish"},
    {"shade_name": "Soft Flame", "category": "Red", "rgb_r": 191, "rgb_g": 83, "rgb_b": 99, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Scarlet", "category": "Red", "rgb_r": 192, "rgb_g": 91, "rgb_b": 96, "lip_type_tag": "Pinkish"},
    {"shade_name": "Modern Fire", "category": "Red", "rgb_r": 197, "rgb_g": 68, "rgb_b": 99, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dreamy Scarlet", "category": "Red", "rgb_r": 198, "rgb_g": 78, "rgb_b": 91, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dreamy Cardinal", "category": "Red", "rgb_r": 199, "rgb_g": 74, "rgb_b": 82, "lip_type_tag": "Pinkish"},
    {"shade_name": "Chilled Crimson", "category": "Red", "rgb_r": 202, "rgb_g": 64, "rgb_b": 97, "lip_type_tag": "Pinkish"},
    {"shade_name": "Twilight Cardinal", "category": "Red", "rgb_r": 204, "rgb_g": 67, "rgb_b": 77, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Ruby", "category": "Red", "rgb_r": 209, "rgb_g": 60, "rgb_b": 79, "lip_type_tag": "Pinkish"},
    {"shade_name": "Vibrant Cherry", "category": "Red", "rgb_r": 211, "rgb_g": 78, "rgb_b": 89, "lip_type_tag": "Pinkish"},
    {"shade_name": "Satin Ruby", "category": "Red", "rgb_r": 211, "rgb_g": 92, "rgb_b": 94, "lip_type_tag": "Pinkish"},
    {"shade_name": "Glossy Fire", "category": "Red", "rgb_r": 213, "rgb_g": 61, "rgb_b": 73, "lip_type_tag": "Pinkish"},
    {"shade_name": "Bold Flame", "category": "Red", "rgb_r": 217, "rgb_g": 62, "rgb_b": 94, "lip_type_tag": "Pinkish"},
    {"shade_name": "Gentle Vermillion", "category": "Red", "rgb_r": 218, "rgb_g": 79, "rgb_b": 78, "lip_type_tag": "Pinkish"},
    {"shade_name": "Velvet Ruby", "category": "Red", "rgb_r": 220, "rgb_g": 75, "rgb_b": 65, "lip_type_tag": "Pinkish"},
    {"shade_name": "Modern Cherry", "category": "Red", "rgb_r": 221, "rgb_g": 96, "rgb_b": 83, "lip_type_tag": "Pinkish"},
    {"shade_name": "Vibrant Wine", "category": "Red", "rgb_r": 221, "rgb_g": 72, "rgb_b": 91, "lip_type_tag": "Pinkish"},
    {"shade_name": "Sheer Ruby", "category": "Red", "rgb_r": 221, "rgb_g": 88, "rgb_b": 82, "lip_type_tag": "Pinkish"},
    {"shade_name": "Subtle Ruby", "category": "Red", "rgb_r": 222, "rgb_g": 35, "rgb_b": 97, "lip_type_tag": "Pinkish"},
    {"shade_name": "Satin Scarlet", "category": "Red", "rgb_r": 222, "rgb_g": 69, "rgb_b": 90, "lip_type_tag": "Pinkish"},
    {"shade_name": "Chilled Cherry", "category": "Red", "rgb_r": 223, "rgb_g": 74, "rgb_b": 67, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Wine", "category": "Red", "rgb_r": 223, "rgb_g": 55, "rgb_b": 81, "lip_type_tag": "Pinkish"},
    {"shade_name": "Velvet Ruby", "category": "Red", "rgb_r": 223, "rgb_g": 69, "rgb_b": 65, "lip_type_tag": "Pinkish"},
    {"shade_name": "Creamy Vermillion", "category": "Red", "rgb_r": 225, "rgb_g": 61, "rgb_b": 93, "lip_type_tag": "Pinkish"},
    {"shade_name": "Tender Scarlet", "category": "Red", "rgb_r": 226, "rgb_g": 62, "rgb_b": 68, "lip_type_tag": "Pinkish"},
    {"shade_name": "Luminous Flame", "category": "Red", "rgb_r": 228, "rgb_g": 86, "rgb_b": 97, "lip_type_tag": "Pinkish"},
    {"shade_name": "Matte Vermillion", "category": "Red", "rgb_r": 229, "rgb_g": 84, "rgb_b": 97, "lip_type_tag": "Pinkish"},
    {"shade_name": "Soft Scarlet", "category": "Red", "rgb_r": 231, "rgb_g": 52, "rgb_b": 88, "lip_type_tag": "Pinkish"},
    {"shade_name": "Vivid Fire", "category": "Red", "rgb_r": 231, "rgb_g": 57, "rgb_b": 74, "lip_type_tag": "Pinkish"},
    {"shade_name": "Vivid Flame", "category": "Red", "rgb_r": 232, "rgb_g": 70, "rgb_b": 50, "lip_type_tag": "Pinkish"},
    {"shade_name": "Radiant Vermillion", "category": "Red", "rgb_r": 232, "rgb_g": 63, "rgb_b": 74, "lip_type_tag": "Pinkish"},
    {"shade_name": "Silky Scarlet", "category": "Red", "rgb_r": 233, "rgb_g": 65, "rgb_b": 56, "lip_type_tag": "Pinkish"},
    {"shade_name": "Sheer Fire", "category": "Red", "rgb_r": 233, "rgb_g": 70, "rgb_b": 72, "lip_type_tag": "Pinkish"},
    {"shade_name": "Twilight Fire", "category": "Red", "rgb_r": 233, "rgb_g": 58, "rgb_b": 91, "lip_type_tag": "Pinkish"},
    {"shade_name": "Warm Poppy", "category": "Red", "rgb_r": 233, "rgb_g": 72, "rgb_b": 88, "lip_type_tag": "Pinkish"},
    {"shade_name": "Tender Ruby", "category": "Red", "rgb_r": 234, "rgb_g": 78, "rgb_b": 89, "lip_type_tag": "Pinkish"},
    {"shade_name": "Matte Fire", "category": "Red", "rgb_r": 234, "rgb_g": 77, "rgb_b": 74, "lip_type_tag": "Pinkish"},
    {"shade_name": "Soft Poppy", "category": "Red", "rgb_r": 234, "rgb_g": 83, "rgb_b": 68, "lip_type_tag": "Pinkish"},
    {"shade_name": "Dewy Poppy", "category": "Red", "rgb_r": 234, "rgb_g": 83, "rgb_b": 49, "lip_type_tag": "Pinkish"},
    {"shade_name": "Modern Vermillion", "category": "Red", "rgb_r": 234, "rgb_g": 81, "rgb_b": 85, "lip_type_tag": "Pinkish"},
    {"shade_name": "Cozy Fire", "category": "Red", "rgb_r": 235, "rgb_g": 39, "rgb_b": 85, "lip_type_tag": "Pinkish"},
    {"shade_name": "Warm Cardinal", "category": "Red", "rgb_r": 235, "rgb_g": 89, "rgb_b": 88, "lip_type_tag": "Pinkish"},
    {"shade_name": "Matte Ruby", "category": "Red", "rgb_r": 236, "rgb_g": 38, "rgb_b": 99, "lip_type_tag": "Pinkish"},
    {"shade_name": "Chilled Fire", "category": "Red", "rgb_r": 237, "rgb_g": 90, "rgb_b": 94, "lip_type_tag": "Pinkish"},
    {"shade_name": "Radiant Flame", "category": "Red", "rgb_r": 237, "rgb_g": 97, "rgb_b": 96, "lip_type_tag": "Pinkish"},
    {"shade_name": "Soft Wine", "category": "Red", "rgb_r": 238, "rgb_g": 70, "rgb_b": 80, "lip_type_tag": "Pinkish"},
    {"shade_name": "Rich Flame", "category": "Red", "rgb_r": 239, "rgb_g": 66, "rgb_b": 70, "lip_type_tag": "Pinkish"},
    {"shade_name": "Gentle Cardinal", "category": "Red", "rgb_r": 244, "rgb_g": 53, "rgb_b": 86, "lip_type_tag": "Pinkish"},
    {"shade_name": "Glossy Poppy", "category": "Red", "rgb_r": 250, "rgb_g": 80, "rgb_b": 89, "lip_type_tag": "Pinkish"},
    {"shade_name": "Tender Cardinal", "category": "Red", "rgb_r": 251, "rgb_g": 44, "rgb_b": 96, "lip_type_tag": "Pinkish"},
    {"shade_name": "Creamy Fire", "category": "Red", "rgb_r": 253, "rgb_g": 67, "rgb_b": 52, "lip_type_tag": "Pinkish"},
    {"shade_name": "Classic Cherry", "category": "Red", "rgb_r": 254, "rgb_g": 100, "rgb_b": 90, "lip_type_tag": "Pinkish"},
    {"shade_name": "Tender Cherry", "category": "Red", "rgb_r": 254, "rgb_g": 91, "rgb_b": 86, "lip_type_tag": "Pinkish"},
    {"shade_name": "Mellow Berry", "category": "Berry", "rgb_r": 46, "rgb_g": 71, "rgb_b": 99, "lip_type_tag": "Brownish"},
    {"shade_name": "Dewy Cranberry", "category": "Berry", "rgb_r": 100, "rgb_g": 38, "rgb_b": 63, "lip_type_tag": "Brownish"},
    {"shade_name": "Velvet Logan", "category": "Berry", "rgb_r": 128, "rgb_g": 41, "rgb_b": 50, "lip_type_tag": "Brownish"},
    {"shade_name": "Silky Logan", "category": "Berry", "rgb_r": 130, "rgb_g": 46, "rgb_b": 46, "lip_type_tag": "Brownish"},
    {"shade_name": "Sheer Berry", "category": "Berry", "rgb_r": 132, "rgb_g": 44, "rgb_b": 113, "lip_type_tag": "Brownish"},
    {"shade_name": "Chilled Cranberry", "category": "Berry", "rgb_r": 132, "rgb_g": 68, "rgb_b": 82, "lip_type_tag": "Brownish"},
    {"shade_name": "Chilled Raspberry", "category": "Berry", "rgb_r": 134, "rgb_g": 85, "rgb_b": 109, "lip_type_tag": "Brownish"},
    {"shade_name": "Tender Bilberry", "category": "Berry", "rgb_r": 137, "rgb_g": 40, "rgb_b": 51, "lip_type_tag": "Brownish"},
    {"shade_name": "Gentle Cranberry", "category": "Berry", "rgb_r": 139, "rgb_g": 40, "rgb_b": 68, "lip_type_tag": "Brownish"},
    {"shade_name": "Vibrant Berry", "category": "Berry", "rgb_r": 142, "rgb_g": 36, "rgb_b": 62, "lip_type_tag": "Brownish"},
    {"shade_name": "Mellow Logan", "category": "Berry", "rgb_r": 144, "rgb_g": 26, "rgb_b": 50, "lip_type_tag": "Brownish"},
    {"shade_name": "Sheer Cranberry", "category": "Berry", "rgb_r": 147, "rgb_g": 20, "rgb_b": 47, "lip_type_tag": "Brownish"},
    {"shade_name": "Bold Cranberry", "category": "Berry", "rgb_r": 147, "rgb_g": 40, "rgb_b": 68, "lip_type_tag": "Brownish"},
    {"shade_name": "Matte Mulberry", "category": "Berry", "rgb_r": 149, "rgb_g": 30, "rgb_b": 83, "lip_type_tag": "Brownish"},
    {"shade_name": "Vivid Logan", "category": "Berry", "rgb_r": 149, "rgb_g": 53, "rgb_b": 140, "lip_type_tag": "Brownish"},
    {"shade_name": "Sheer Berry", "category": "Berry", "rgb_r": 151, "rgb_g": 66, "rgb_b": 73, "lip_type_tag": "Brownish"},
    {"shade_name": "Rich Cranberry", "category": "Berry", "rgb_r": 155, "rgb_g": 50, "rgb_b": 90, "lip_type_tag": "Brownish"},
    {"shade_name": "Vibrant Raspberry", "category": "Berry", "rgb_r": 158, "rgb_g": 44, "rgb_b": 44, "lip_type_tag": "Brownish"},
    {"shade_name": "Modern Bilberry", "category": "Berry", "rgb_r": 158, "rgb_g": 51, "rgb_b": 61, "lip_type_tag": "Brownish"},
    {"shade_name": "Dewy Cranberry", "category": "Berry", "rgb_r": 159, "rgb_g": 24, "rgb_b": 44, "lip_type_tag": "Brownish"},
    {"shade_name": "Radiant Logan", "category": "Berry", "rgb_r": 159, "rgb_g": 47, "rgb_b": 86, "lip_type_tag": "Brownish"},
    {"shade_name": "Warm Cranberry", "category": "Berry", "rgb_r": 160, "rgb_g": 15, "rgb_b": 48, "lip_type_tag": "Brownish"},
    {"shade_name": "Vibrant Logan", "category": "Berry", "rgb_r": 160, "rgb_g": 19, "rgb_b": 20, "lip_type_tag": "Brownish"},
    {"shade_name": "Matte Berry", "category": "Berry", "rgb_r": 162, "rgb_g": 83, "rgb_b": 86, "lip_type_tag": "Brownish"},
    {"shade_name": "Tender Raspberry", "category": "Berry", "rgb_r": 165, "rgb_g": 59, "rgb_b": 79, "lip_type_tag": "Brownish"},
    {"shade_name": "Creamy Bilberry", "category": "Berry", "rgb_r": 168, "rgb_g": 13, "rgb_b": 31, "lip_type_tag": "Brownish"},
    {"shade_name": "Soft Berry", "category": "Berry", "rgb_r": 168, "rgb_g": 38, "rgb_b": 40, "lip_type_tag": "Brownish"},
    {"shade_name": "Cozy Raspberry", "category": "Berry", "rgb_r": 168, "rgb_g": 42, "rgb_b": 64, "lip_type_tag": "Brownish"},
    {"shade_name": "Creamy Mulberry", "category": "Berry", "rgb_r": 170, "rgb_g": 34, "rgb_b": 96, "lip_type_tag": "Brownish"},
    {"shade_name": "Mellow Mulberry", "category": "Berry", "rgb_r": 171, "rgb_g": 59, "rgb_b": 72, "lip_type_tag": "Brownish"},
    {"shade_name": "Glossy Cranberry", "category": "Berry", "rgb_r": 172, "rgb_g": 0, "rgb_b": 58, "lip_type_tag": "Brownish"},
    {"shade_name": "Vivid Raspberry", "category": "Berry", "rgb_r": 176, "rgb_g": 16, "rgb_b": 32, "lip_type_tag": "Brownish"},
    {"shade_name": "Vivid Cranberry", "category": "Berry", "rgb_r": 177, "rgb_g": 34, "rgb_b": 82, "lip_type_tag": "Brownish"},
    {"shade_name": "Satin Berry", "category": "Berry", "rgb_r": 178, "rgb_g": 33, "rgb_b": 70, "lip_type_tag": "Brownish"},
    {"shade_name": "Warm Bilberry", "category": "Berry", "rgb_r": 178, "rgb_g": 73, "rgb_b": 87, "lip_type_tag": "Brownish"},
    {"shade_name": "Dreamy Bilberry", "category": "Berry", "rgb_r": 178, "rgb_g": 0, "rgb_b": 50, "lip_type_tag": "Brownish"},
    {"shade_name": "Classic Bilberry", "category": "Berry", "rgb_r": 178, "rgb_g": 48, "rgb_b": 48, "lip_type_tag": "Brownish"},
    {"shade_name": "Matte Cranberry", "category": "Berry", "rgb_r": 213, "rgb_g": 23, "rgb_b": 104, "lip_type_tag": "Brownish"},
    {"shade_name": "Subtle Berry", "category": "Berry", "rgb_r": 228, "rgb_g": 0, "rgb_b": 104, "lip_type_tag": "Brownish"},
    {"shade_name": "Cinnamon", "category": "Brown", "rgb_r": 155, "rgb_g": 85, "rgb_b": 65, "lip_type_tag": "Brownish"},
    {"shade_name": "Spice Brown", "category": "Brown", "rgb_r": 160, "rgb_g": 90, "rgb_b": 70, "lip_type_tag": "Brownish"},
    {"shade_name": "Terracotta", "category": "Coral", "rgb_r": 180, "rgb_g": 100, "rgb_b": 80, "lip_type_tag": "Brownish"},
    {"shade_name": "Mauve Bliss", "category": "Mauve", "rgb_r": 170, "rgb_g": 110, "rgb_b": 130, "lip_type_tag": "Brownish"},
    {"shade_name": "Warm Nude", "category": "Nude", "rgb_r": 165, "rgb_g": 120, "rgb_b": 100, "lip_type_tag": "Brownish"},
    {"shade_name": "Caramel Kiss", "category": "Nude", "rgb_r": 175, "rgb_g": 125, "rgb_b": 95, "lip_type_tag": "Brownish"},
    {"shade_name": "Sheer Flame", "category": "Red", "rgb_r": 142, "rgb_g": 38, "rgb_b": 34, "lip_type_tag": "Brownish"},
    {"shade_name": "Cozy Poppy", "category": "Red", "rgb_r": 144, "rgb_g": 34, "rgb_b": 22, "lip_type_tag": "Brownish"},
    {"shade_name": "Matte Flame", "category": "Red", "rgb_r": 153, "rgb_g": 65, "rgb_b": 61, "lip_type_tag": "Brownish"},
    {"shade_name": "Mellow Wine", "category": "Red", "rgb_r": 181, "rgb_g": 61, "rgb_b": 82, "lip_type_tag": "Brownish"},
    {"shade_name": "Soft Cardinal", "category": "Red", "rgb_r": 182, "rgb_g": 38, "rgb_b": 49, "lip_type_tag": "Brownish"},
    {"shade_name": "Radiant Ruby", "category": "Red", "rgb_r": 183, "rgb_g": 29, "rgb_b": 50, "lip_type_tag": "Brownish"},
    {"shade_name": "Silky Crimson", "category": "Red", "rgb_r": 184, "rgb_g": 18, "rgb_b": 43, "lip_type_tag": "Brownish"},
    {"shade_name": "Chilled Scarlet", "category": "Red", "rgb_r": 184, "rgb_g": 29, "rgb_b": 61, "lip_type_tag": "Brownish"},
    {"shade_name": "Silky Fire", "category": "Red", "rgb_r": 184, "rgb_g": 7, "rgb_b": 34, "lip_type_tag": "Brownish"},
    {"shade_name": "Modern Wine", "category": "Red", "rgb_r": 185, "rgb_g": 40, "rgb_b": 45, "lip_type_tag": "Brownish"},
    {"shade_name": "Cozy Wine", "category": "Red", "rgb_r": 186, "rgb_g": 53, "rgb_b": 60, "lip_type_tag": "Brownish"},
    {"shade_name": "Classic Ruby", "category": "Red", "rgb_r": 187, "rgb_g": 24, "rgb_b": 19, "lip_type_tag": "Brownish"},
    {"shade_name": "Creamy Crimson", "category": "Red", "rgb_r": 187, "rgb_g": 68, "rgb_b": 74, "lip_type_tag": "Brownish"},
    {"shade_name": "Satin Cherry", "category": "Red", "rgb_r": 187, "rgb_g": 50, "rgb_b": 92, "lip_type_tag": "Brownish"},
    {"shade_name": "Mellow Fire", "category": "Red", "rgb_r": 187, "rgb_g": 57, "rgb_b": 95, "lip_type_tag": "Brownish"},
    {"shade_name": "Classic Poppy", "category": "Red", "rgb_r": 187, "rgb_g": 14, "rgb_b": 99, "lip_type_tag": "Brownish"},
    {"shade_name": "Radiant Wine", "category": "Red", "rgb_r": 187, "rgb_g": 60, "rgb_b": 90, "lip_type_tag": "Brownish"},
    {"shade_name": "Silky Cherry", "category": "Red", "rgb_r": 188, "rgb_g": 50, "rgb_b": 80, "lip_type_tag": "Brownish"},
    {"shade_name": "Vibrant Flame", "category": "Red", "rgb_r": 190, "rgb_g": 43, "rgb_b": 36, "lip_type_tag": "Brownish"},
    {"shade_name": "Vivid Cardinal", "category": "Red", "rgb_r": 190, "rgb_g": 36, "rgb_b": 70, "lip_type_tag": "Brownish"},
    {"shade_name": "Velvet Cherry", "category": "Red", "rgb_r": 193, "rgb_g": 62, "rgb_b": 48, "lip_type_tag": "Brownish"},
    {"shade_name": "Radiant Fire", "category": "Red", "rgb_r": 193, "rgb_g": 42, "rgb_b": 51, "lip_type_tag": "Brownish"},
    {"shade_name": "Cozy Scarlet", "category": "Red", "rgb_r": 196, "rgb_g": 19, "rgb_b": 4, "lip_type_tag": "Brownish"},
    {"shade_name": "Sheer Poppy", "category": "Red", "rgb_r": 196, "rgb_g": 55, "rgb_b": 89, "lip_type_tag": "Brownish"},
    {"shade_name": "Modern Poppy", "category": "Red", "rgb_r": 196, "rgb_g": 3, "rgb_b": 43, "lip_type_tag": "Brownish"},
    {"shade_name": "Subtle Wine", "category": "Red", "rgb_r": 197, "rgb_g": 48, "rgb_b": 87, "lip_type_tag": "Brownish"},
    {"shade_name": "Twilight Ruby", "category": "Red", "rgb_r": 198, "rgb_g": 15, "rgb_b": 47, "lip_type_tag": "Brownish"},
    {"shade_name": "Glossy Ruby", "category": "Red", "rgb_r": 198, "rgb_g": 46, "rgb_b": 84, "lip_type_tag": "Brownish"},
    {"shade_name": "Cozy Crimson", "category": "Red", "rgb_r": 199, "rgb_g": 21, "rgb_b": 61, "lip_type_tag": "Brownish"},
    {"shade_name": "Twilight Flame", "category": "Red", "rgb_r": 200, "rgb_g": 44, "rgb_b": 64, "lip_type_tag": "Brownish"},
    {"shade_name": "Dewy Flame", "category": "Red", "rgb_r": 200, "rgb_g": 15, "rgb_b": 46, "lip_type_tag": "Brownish"},
    {"shade_name": "Creamy Poppy", "category": "Red", "rgb_r": 201, "rgb_g": 45, "rgb_b": 56, "lip_type_tag": "Brownish"},
    {"shade_name": "Classic Wine", "category": "Red", "rgb_r": 202, "rgb_g": 41, "rgb_b": 46, "lip_type_tag": "Brownish"},
    {"shade_name": "Tender Wine", "category": "Red", "rgb_r": 203, "rgb_g": 45, "rgb_b": 33, "lip_type_tag": "Brownish"},
    {"shade_name": "Bold Scarlet", "category": "Red", "rgb_r": 204, "rgb_g": 8, "rgb_b": 36, "lip_type_tag": "Brownish"},
    {"shade_name": "Gentle Scarlet", "category": "Red", "rgb_r": 204, "rgb_g": 32, "rgb_b": 16, "lip_type_tag": "Brownish"},
    {"shade_name": "Mellow Scarlet", "category": "Red", "rgb_r": 204, "rgb_g": 3, "rgb_b": 14, "lip_type_tag": "Brownish"},
    {"shade_name": "Soft Ruby", "category": "Red", "rgb_r": 205, "rgb_g": 65, "rgb_b": 67, "lip_type_tag": "Brownish"},
    {"shade_name": "Chilled Flame", "category": "Red", "rgb_r": 205, "rgb_g": 0, "rgb_b": 67, "lip_type_tag": "Brownish"},
    {"shade_name": "Subtle Fire", "category": "Red", "rgb_r": 206, "rgb_g": 18, "rgb_b": 32, "lip_type_tag": "Brownish"},
    {"shade_name": "Creamy Cardinal", "category": "Red", "rgb_r": 207, "rgb_g": 29, "rgb_b": 89, "lip_type_tag": "Brownish"},
    {"shade_name": "Twilight Scarlet", "category": "Red", "rgb_r": 208, "rgb_g": 1, "rgb_b": 30, "lip_type_tag": "Brownish"},
    {"shade_name": "Vibrant Scarlet", "category": "Red", "rgb_r": 208, "rgb_g": 1, "rgb_b": 11, "lip_type_tag": "Brownish"},
    {"shade_name": "Vivid Ruby", "category": "Red", "rgb_r": 209, "rgb_g": 18, "rgb_b": 27, "lip_type_tag": "Brownish"},
    {"shade_name": "Vivid Cherry", "category": "Red", "rgb_r": 209, "rgb_g": 23, "rgb_b": 70, "lip_type_tag": "Brownish"},
    {"shade_name": "Vivid Scarlet", "category": "Red", "rgb_r": 212, "rgb_g": 2, "rgb_b": 14, "lip_type_tag": "Brownish"},
    {"shade_name": "Modern Scarlet", "category": "Red", "rgb_r": 212, "rgb_g": 27, "rgb_b": 64, "lip_type_tag": "Brownish"},
    {"shade_name": "Silky Ruby", "category": "Red", "rgb_r": 212, "rgb_g": 58, "rgb_b": 41, "lip_type_tag": "Brownish"},
    {"shade_name": "Silky Ruby", "category": "Red", "rgb_r": 214, "rgb_g": 35, "rgb_b": 82, "lip_type_tag": "Brownish"},
    {"shade_name": "Twilight Crimson", "category": "Red", "rgb_r": 214, "rgb_g": 8, "rgb_b": 70, "lip_type_tag": "Brownish"},
    {"shade_name": "Soft Crimson", "category": "Red", "rgb_r": 217, "rgb_g": 16, "rgb_b": 14, "lip_type_tag": "Brownish"},
    {"shade_name": "Rich Vermillion", "category": "Red", "rgb_r": 217, "rgb_g": 24, "rgb_b": 32, "lip_type_tag": "Brownish"},
    {"shade_name": "Sheer Scarlet", "category": "Red", "rgb_r": 218, "rgb_g": 1, "rgb_b": 64, "lip_type_tag": "Brownish"},
    {"shade_name": "Dreamy Crimson", "category": "Red", "rgb_r": 220, "rgb_g": 41, "rgb_b": 35, "lip_type_tag": "Brownish"},
    {"shade_name": "Matte Cardinal", "category": "Red", "rgb_r": 220, "rgb_g": 0, "rgb_b": 44, "lip_type_tag": "Brownish"},
    {"shade_name": "Glossy Ruby", "category": "Red", "rgb_r": 223, "rgb_g": 52, "rgb_b": 67, "lip_type_tag": "Brownish"},
    {"shade_name": "Classic Scarlet", "category": "Red", "rgb_r": 223, "rgb_g": 41, "rgb_b": 78, "lip_type_tag": "Brownish"},
    {"shade_name": "Silky Flame", "category": "Red", "rgb_r": 224, "rgb_g": 46, "rgb_b": 32, "lip_type_tag": "Brownish"},
    {"shade_name": "Rich Cardinal", "category": "Red", "rgb_r": 224, "rgb_g": 38, "rgb_b": 46, "lip_type_tag": "Brownish"},
    {"shade_name": "Creamy Wine", "category": "Red", "rgb_r": 224, "rgb_g": 59, "rgb_b": 53, "lip_type_tag": "Brownish"},
    {"shade_name": "Gentle Fire", "category": "Red", "rgb_r": 225, "rgb_g": 41, "rgb_b": 72, "lip_type_tag": "Brownish"},
    {"shade_name": "Mellow Flame", "category": "Red", "rgb_r": 225, "rgb_g": 17, "rgb_b": 42, "lip_type_tag": "Brownish"},
    {"shade_name": "Radiant Cardinal", "category": "Red", "rgb_r": 225, "rgb_g": 36, "rgb_b": 75, "lip_type_tag": "Brownish"},
    {"shade_name": "Warm Wine", "category": "Red", "rgb_r": 225, "rgb_g": 16, "rgb_b": 32, "lip_type_tag": "Brownish"},
    {"shade_name": "Bold Cherry", "category": "Red", "rgb_r": 226, "rgb_g": 25, "rgb_b": 73, "lip_type_tag": "Brownish"},
    {"shade_name": "Classic Crimson", "category": "Red", "rgb_r": 228, "rgb_g": 0, "rgb_b": 79, "lip_type_tag": "Brownish"},
    {"shade_name": "Satin Flame", "category": "Red", "rgb_r": 228, "rgb_g": 0, "rgb_b": 33, "lip_type_tag": "Brownish"},
    {"shade_name": "Cozy Vermillion", "category": "Red", "rgb_r": 228, "rgb_g": 0, "rgb_b": 62, "lip_type_tag": "Brownish"},
    {"shade_name": "Creamy Scarlet", "category": "Red", "rgb_r": 229, "rgb_g": 35, "rgb_b": 34, "lip_type_tag": "Brownish"},
    {"shade_name": "Gentle Poppy", "category": "Red", "rgb_r": 229, "rgb_g": 30, "rgb_b": 27, "lip_type_tag": "Brownish"},
    {"shade_name": "Glossy Cardinal", "category": "Red", "rgb_r": 229, "rgb_g": 47, "rgb_b": 49, "lip_type_tag": "Brownish"},
    {"shade_name": "Modern Cardinal", "category": "Red", "rgb_r": 229, "rgb_g": 0, "rgb_b": 54, "lip_type_tag": "Brownish"},
    {"shade_name": "Dreamy Poppy", "category": "Red", "rgb_r": 230, "rgb_g": 8, "rgb_b": 96, "lip_type_tag": "Brownish"},
    {"shade_name": "Twilight Poppy", "category": "Red", "rgb_r": 231, "rgb_g": 66, "rgb_b": 24, "lip_type_tag": "Brownish"},
    {"shade_name": "Vibrant Cardinal", "category": "Red", "rgb_r": 231, "rgb_g": 0, "rgb_b": 96, "lip_type_tag": "Brownish"},
    {"shade_name": "Velvet Flame", "category": "Red", "rgb_r": 232, "rgb_g": 47, "rgb_b": 44, "lip_type_tag": "Brownish"},
    {"shade_name": "Classic Vermillion", "category": "Red", "rgb_r": 232, "rgb_g": 70, "rgb_b": 23, "lip_type_tag": "Brownish"},
    {"shade_name": "Mellow Cardinal", "category": "Red", "rgb_r": 248, "rgb_g": 33, "rgb_b": 49, "lip_type_tag": "Brownish"},
    {"shade_name": "Tender Fire", "category": "Red", "rgb_r": 250, "rgb_g": 66, "rgb_b": 28, "lip_type_tag": "Brownish"},
    {"shade_name": "Classic Cardinal", "category": "Red", "rgb_r": 250, "rgb_g": 5, "rgb_b": 75, "lip_type_tag": "Brownish"},
    {"shade_name": "Silky Wine", "category": "Red", "rgb_r": 250, "rgb_g": 1, "rgb_b": 61, "lip_type_tag": "Brownish"},
    {"shade_name": "Luminous Fire", "category": "Red", "rgb_r": 255, "rgb_g": 50, "rgb_b": 32, "lip_type_tag": "Brownish"},
    {"shade_name": "Modern Raspberry", "category": "Berry", "rgb_r": 85, "rgb_g": 0, "rgb_b": 1, "lip_type_tag": "Dark"},
    {"shade_name": "Dreamy Cranberry", "category": "Berry", "rgb_r": 88, "rgb_g": 21, "rgb_b": 30, "lip_type_tag": "Dark"},
    {"shade_name": "Silky Berry", "category": "Berry", "rgb_r": 96, "rgb_g": 34, "rgb_b": 39, "lip_type_tag": "Dark"},
    {"shade_name": "Subtle Cranberry", "category": "Berry", "rgb_r": 99, "rgb_g": 15, "rgb_b": 40, "lip_type_tag": "Dark"},
    {"shade_name": "Twilight Cranberry", "category": "Berry", "rgb_r": 115, "rgb_g": 25, "rgb_b": 25, "lip_type_tag": "Dark"},
    {"shade_name": "Deep Berry", "category": "Berry", "rgb_r": 120, "rgb_g": 50, "rgb_b": 70, "lip_type_tag": "Dark"},
    {"shade_name": "Glossy Bilberry", "category": "Berry", "rgb_r": 138, "rgb_g": 1, "rgb_b": 13, "lip_type_tag": "Dark"},
    {"shade_name": "Mellow Raspberry", "category": "Berry", "rgb_r": 148, "rgb_g": 2, "rgb_b": 32, "lip_type_tag": "Dark"},
    {"shade_name": "Raisin", "category": "Brown", "rgb_r": 80, "rgb_g": 35, "rgb_b": 45, "lip_type_tag": "Dark"},
    {"shade_name": "Midnight Mauve", "category": "Mauve", "rgb_r": 90, "rgb_g": 40, "rgb_b": 65, "lip_type_tag": "Dark"},
    {"shade_name": "Plum Wine", "category": "Plum", "rgb_r": 100, "rgb_g": 35, "rgb_b": 60, "lip_type_tag": "Dark"},
    {"shade_name": "Tender Poppy", "category": "Red", "rgb_r": 57, "rgb_g": 30, "rgb_b": 29, "lip_type_tag": "Dark"},
    {"shade_name": "Burgundy", "category": "Red", "rgb_r": 110, "rgb_g": 40, "rgb_b": 50, "lip_type_tag": "Dark"},
    {"shade_name": "Cherry Red", "category": "Red", "rgb_r": 130, "rgb_g": 45, "rgb_b": 55, "lip_type_tag": "Dark"},
]


MAX_RGB_DISTANCE = math.sqrt(255 ** 2 * 3)  # ≈ 441.67


def _euclidean(a: tuple, b: tuple) -> float:
    return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2)


def _similarity_pct(a: tuple, b: tuple) -> float:
    distance = _euclidean(a, b)
    return round(max(0, (1 - distance / MAX_RGB_DISTANCE) * 100), 1)


def get_top3(lip_type: str, rgb: tuple) -> list[dict]:
    candidates = [ls for ls in lipstick_database if ls["lip_type_tag"] == lip_type]
    scored = [
        {
            "shade_name": ls["shade_name"],
            "category": ls["category"],
            "score": _similarity_pct(rgb, (ls["rgb_r"], ls["rgb_g"], ls["rgb_b"])),
            "rgb": {"r": ls["rgb_r"], "g": ls["rgb_g"], "b": ls["rgb_b"]},
        }
        for ls in candidates
    ]
    return sorted(scored, key=lambda x: x["score"], reverse=True)[:3]
